### ISSUE TITLE
https://dl.dropboxusercontent.com/u/6771946/icons/flat.png 404 not found

### ISSUE THREAD

**Issue by sebadelmar** [halgatewood/file-directory-list#10]
Thank you very much for the script, can you upload the flat.png file to the repository?

**Comment by halgatewood** [comment]
Can you try this: https://www.dropbox.com/s/lzxi5abx2gaj84q/flat.png?dl=0

**Comment by seballero** [comment]
Thanks!!  :D

**Comment by Jogai** [comment]
For anyone who needs more icons: https://github.com/redbooth/free-file-icons

**Comment by RiPPERD** [comment]
> 
> 
> For anyone who needs more icons: https://github.com/redbooth/free-file-icons

how do i add these icons? or custom icons? im after APK icon

**Comment by Jogai** [comment]
Add a css class for your specific icon and point to that specific icon as background url.
