### ISSUE TITLE
Size shows not working

### ISSUE THREAD

**Issue by byman64** [halgatewood/file-directory-list#12]
Hi, thx for share your work.

I just downloaded the last version 1.9 and **folder size** always shows  4kb.
[screenshot with folder size missing](https://prnt.sc/gg4s1d)

note:
I have an old version without version inside and folder size works fine.
In this version I only fixed  the icons becuase they were missing .
[screenshot with folder size](https://prnt.sc/gg4xb2)

Any idea why in the new version size is wrong?

**UPDATE - 1**
In the oldone there is a call to the function : format_size_from_bytes(foldersize($file))
It is missing in the version 1.9
[screenshot with code compared](https://prnt.sc/gg51u6)

**UPDATE - 2** 
You can download the UNKNOWN version with folder size feature until  2017-10-31
[unknown version with folder size feature](http://www.quakearea.com/owncloud/index.php/s/vXrrkDTGc9QmUIf)

**UPDATE - 3**
Just updated your last version 1.9 adding the feature for folder size.
I called it 1.9.1
Changes:
- Comments label:  "byman"
- Added 2 functions :  format_size_from_bytes() and  foldersize()
- Changed the function display_block()

You can download from the following link until 2017-10-31
[file directory-list with folder size](http://www.quakearea.com/owncloud/index.php/s/GrKpytAZhxgc6we)

**UPDATE - 4**
I am working on some other little stuff:
- title (splitted in 3 title1,2,3)
- better view on smarth phones. (meta viewport)
Just little changes in progress...
Here a [preview](https://image.prntscr.com/image/jGHoyb4zSe6wi7wmmyOb2Q.png)

***[OT]
Sorry but I dont know how github works, I have an account, I need to read some. Let me give you my new code  with a simple link...1.9.2 will arrive soon.

I hope you will include the folder size feature in your next version.

regards

thx

**Comment by georgeinmexico** [comment]
I agree that file sizes display correctly, but all folders list as 4kb in size.

**Comment by halgatewood** [comment]
I just got the folder sizes displayed correctly with a count of how many files are in them. New script and demo here: https://halgatewood.com/free/file-directory-list/
