### ISSUE TITLE
folder named aaa.bbb will show as file

### ISSUE THREAD

**Issue by yurenchen000** [halgatewood/file-directory-list#4]
https://github.com/halgatewood/file-directory-list/blob/b48be52670f75250f1383cfb0374bffb10f99794/index.php#L139

I fixed this problem by change to:

``` php
if( is_dir($file))
    $file_ext = "dir";
else
    $file_ext = getFileExt($file);
```

**Comment by halgatewood** [comment]
Thank you! I just merged it with master.
