### ISSUE TITLE
Preventing folder listing

### ISSUE THREAD

**Issue by 2braincells2go** [halgatewood/file-directory-list#7]
Firstly, great clean script, thank you for sharing!

After few attempts, I cannot figure out how to prevent folder listing. Like to have only files listed, is this possible?

If I may make a few suggestions to make your dir listing script better:

1) Option to remove filename extension
2) option to use title tag in file name as listing

Thanks again for sharing, really useful script.

Woody

**Comment by halgatewood** [comment]
Since it's just an index.php file you can remove and change it however you need. I don't want to load it up with too many settings. The function to update is `display_block` inside there you can remove the `<a>` tags and modify the titles as you need.
